config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  resources :products
  devise_for :users
  root to: 'page#home'
  get '/about',to: 'page#about'
resources :categories, except: [:delete, :show]
resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

validates_presence_of :name
validates_uniqueness_of :name
has_many :product_categories
has_many :products , through: :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
 validates_presence_of :summary
 validates_presence_of :description

  has_many :product_categories
  has_many :categories, through: :product_categories
   belongs_to :user
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
belongs_to :product
belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, dependent: :destroy
  validates_presence_of :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_params, if: :devise_controller?

  def configure_permitted_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :link])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :link])

  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

access all: [:show, :index], user: {except: [:destroy, :new, :edit, :update, :create]}, site_admin: :all
  def index
    @categories = Category.all
  end

   def new
   @category = Category.new
   end

    def edit
      @category = Category.find(params[:id])
    end


   def create
     @category = Category.new(category_params)
        if @category.save
         flash[:success] = "Category has been successfully created"
         redirect_to categories_path
        else
         render 'new'
       end
   end

   def update
     @category = Category.find(params[:id])
     if @category.update(category_params)
      flash[:success] = "Category has been successfully updated"
        redirect_to categories_path
      else
       render 'edit'
     end
   end

private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

      if @product.save
        flash[:notice] = 'Product was successfully created.'
        redirect_to @product
      else
          render 'new'
      end
    # end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
      if @product.update(product_params)
        flash[:notice] = 'Product was successfully updated.'
        redirect_to @product
      else
        render 'edit'
      end
    # end
  end

  # DELETE /products/1
  # DELETE /products/1.json

    def destroy
      @product.destroy

        respond_to do |format|
          format.html { redirect_to products_url, notice: 'Product was successfully deleted.' }
          format.json { head :no_content }
          format.js   { render :layout => false }
        end
      end








  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:summary, :description, category_ids: [])
    end
    #
    def require_same_user
      if !logged_in?(:site_admin) and current_user != @product.user
        flash[:notice] = "You can only edit or delete your own products"
        redirect_to root_path
      end
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(obj, :html => {class: "form-horizontal", row: "form"}) do |f| %>
<div class="form-group">
<div class="control-label col-sm-2">
    <%= f.label :name %>
    </div>
    <div class="col-sm-8">
    <%= f.text_field :name, class: "form-control",placeholder: "Category Name", autofocus: true%>
  </div>
</div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%=f.submit "Create Category",class: "btn btn-primary btn-large"%>
      </div>
    </div>
    <% end %>

app/views/categories/edit.html.erb
<div class="container">
    
<h1 class="text-center">Edit this category</h1>
<%= render 'form', :obj => @category %>
</div>

app/views/categories/index.html.erb
<div class="container">
    
<br><br>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>All Categories</th>
      <th>View</th>
    </tr>
  </thead>
  <tbody>
 <% @categories.each do |category_item| %>

  <tr>
    <th scope="row"><%=category_item.id%></th>
    <td>  <%= category_item.name %></td>
    <td> <%= link_to "All Products", "#" ,class: "btn btn-primary" %> </td>
  </tr>

<% end %>
</tbody>
</table>

</div>

app/views/categories/new.html.erb
<div class="container">
    

<h1 class="text-center"> New Category</h1>
<%= render 'form', :obj => @category %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SundayMarket</title>
    <%= csrf_meta_tags %>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


 <!-- start of navbar -->

 <%= render 'shared/app_navbar' %>


 <!-- end of navbar -->

        
  
            <%= yield %>

      

          <%= render 'shared/alerts' %>
          <!-- start of footer -->
           <%= render 'shared/app_footer' %>
          <!-- end of footer -->

  </body>
</html>

app/views/page/about.html.erb
<div class="container">
    

  <h1>Page#about</h1>
  <p>Find me in app/views/page/about.html.erb</p>
  <%= link_to "Home", root_path %>
</div>

app/views/page/home.html.erb
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <%= image_tag("/assets/market6.jpg", class: "second-slide")  %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-left">
              <!-- <h1>Sunday Market</h1> -->
              <!-- <p>Come here to Explore more about us </p> -->
              <!-- <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p> -->
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("/assets/market2.jpg", class: "second-slide")  %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block">
              <h1>Sunday Market</h1>
              <p>Your full stop shopping destination</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag("/assets/market3.jpg", class: "third-slide")  %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-right">
              <h1>Sunday Market</h1>
              <p>Visit us. Satisfaction guaranteed</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <%= fa_icon "check 4x", class: "text-muted" %>
          <h2>Heading</h2>
          <p>Quality Guaranteed is our promise. Everytime you buy from our market, we assure you of quality stuff as well as the best price. We serve well and satisy your needs.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= fa_icon "handshake-o  4x", class: "text-muted" %>
          <h2>Heading</h2>
          <p>Join hands with us so that you can feed your family great, quality food. We have all the products you might want this week. So start boosting the health of your loved ones.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= fa_icon "home 4x", class: "text-muted" %>
          <h2>Heading</h2>
          <p>We also offer a Home delivery service, where all the products will be delivered to your home without any extra charge and also we assure the quality of products delivered.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
            <!-- <img class="featurette-image img-fluid mx-auto" data-src="http://via.placeholder.com/500x500" alt="Generic placeholder image"> -->
          <%= image_tag "banana.jpg", class: "featurette-image img-fluid mx-auto rounded" %>
            <!-- Place your own image tag  -->
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <%= image_tag "berry.jpg", class: "featurette-image img-fluid mx-auto rounded" %>
          <!-- Place your own image tag  -->
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <%= image_tag "basket.jpg", class: "featurette-image img-fluid mx-auto rounded" %>
          <!-- Place your own image tag  -->
        </div>
      </div>




    </div><!-- /.container -->

app/views/products/_form.html.erb
<%= form_for(obj) do |f| %>
  <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |error| %>
        <%= js add_gritter(error, title: "Gaurav Gualti") %>
      <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control", placeholder: "Enter the Summary here.",autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description,rows: 5, class: "form-control",placeholder: "Enter the Description here." %>
  </div>


  <div class="form-group">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>

     <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text} %>
     <% end %>
 </div>

 <div class="form-group">
   <%= f.submit "Submit",class: "btn btn-primary btn-lg" %>
 </div>
<% end %>

app/views/products/destroy.js.erb
$(".prod-<%=@product.id %>").fadeOut(500, function(){
   $(this).remove();
});

app/views/products/edit.html.erb
<div class="container">
    
<h1>Editing Product</h1>

<%= render 'form', obj: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

</div>

app/views/products/index.html.erb
<div class="container">



<!-- <p id="notice"><%= notice %></p> -->
<br>
<h1 class="text-center"> All Products available this Market</h1>
<br>

<div class="row">
<% @products.each do |product| %>
<div class="col-md-4">
<div class="card prod-<%=product.id%>" style="width: 19rem;">
  <img class="card-img-top" src="<%= product.thumb_image %>" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title">
      <%= product.summary %>
    </h4>
    <p class="card-text">
      <%= product.description %>
    </p>



    <% if current_user == product.user || logged_in?(:site_admin) %>
           <%= link_to 'Show', product, class: "btn btn-sm btn-primary" %>
           | <%= link_to 'Edit', edit_product_path(product), class: "btn btn-sm btn-warning" %>
            | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger", remote: true %>
    <% else %>
          <div class="row">
            <div class="col-md-4"></div>
              <div class="col-md-4">
                  <%= link_to 'Show', product, class: "btn btn-sm btn-primary btn-block" %>
              </div>
          </div>
    <% end %>

<hr><% if product.categories.count>0  %>
  <% product.categories.each do |cat| %>
    <span class="badge badge-dark badge-pill badge-cat"><%= cat.name %></span>
  <% end %>
<% end %>



  </div>
</div>
<br>
</div>
<% end %>
</div>

</div>

app/views/products/new.html.erb
<div class="container">
<div class="row">

<div class="col-md-7 spacing">

<h1>New Product</h1>

<%= render 'form', obj: @product %>

<%= link_to 'Back', products_path %>
</div>

<div class="col-md-3 offset-md-2 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Tip of The day</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
        </div>
        </div>

app/views/products/show.html.erb
<div class="container">
<br>
<div class="row">

  <div class="col-md-6">
  <img class="card-img-top" src="<%= @product.main_image %>" alt="Card image cap">
  </div>


<div class="col-md-6">

<h2>Summary</h2>
<p>

  <%= @product.summary %>

</p>

<h2>Description</h2>
    <p>
        <%= @product.description %>
    </p>


<% if @product.user %>
  <button type="button" class="btn btn-dark btn-usr">Check the Seller</button>
<% end %>

 <span class="random">
   <% if @product.user.name? %>
      <%= link_to @product.user.name, user_path(@product.user), class: "btn btn-light" %>
   <% else %>
      <%= link_to @product.user.email, user_path(@product.user), class: "btn btn-light" %>
   <% end %>
 </span>

<% if @product.user == current_user %>
 <%= link_to 'Edit', edit_product_path(@product) %> |
 <%= link_to 'Back', products_path %>
<% end %>
</div>

</div>
</div>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
<%= js add_gritter(flash[:alert], title: "Gaurav Gualti") %>
<% elsif flash[:error] %>
<%= js add_gritter(flash[:error], title: "Gaurav Gualti") %>
<% else %>
<%= js add_gritter(flash[:notice], title: "Gaurav Gualti") %>
<% end %>

app/views/shared/_app_footer.html.erb
<div class="container">
  <hr class="featurette-divider">
  <footer>
    <p class="float-right"><a href="#"> Back to top</a></p>

    <!-- <p class="float-right insert"> </p>
<button type="button" class="btn btn-dark btn-session">Dark</button> -->
    <p class="float-right"> Session started @ </p>
     <p>&copy; 2017 Gaurav Gulati, Inc. ; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
   </footer>
</div>

app/views/shared/_app_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">SundayMarket</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to  "Home", root_path, class: "nav-link" %>
     </li>
      <li class="nav-item">
        <%= link_to  "About", about_path,class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to  "All Products", products_path,class: "nav-link" %>
      </li>

    </ul>
  <% if !current_user %>
               <%= link_to "Login", new_user_session_path, class: "nav-link" %>
               <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
  <% else %>
         <%= link_to current_user.email, edit_user_registration_path,class: "nav-link" %>
         <%= link_to("Logout", destroy_user_session_path, :method => :delete ,class: "nav-link") %>
  <% end %>

  </div>
</nav>

app/views/users/index.html.erb
<div class="container">

<br><br>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email Id</th>
      <th>URL</th>
      <th>Offerings</th>
    </tr>
  </thead>
  <tbody>
 <% @users.each do |user| %>

  <tr>
    <th scope="row"><%=user.id%></th>
    <% if user.name? %>
    <td> <%= link_to user.name, user_path(user) %> </td>
    <% else %>
    <td> Guest Seller </td>
    <% end %>
    <td>  <%= link_to user.email, user_path(user) %></td>
    <td> <%= link_to user.link, user.link if user.link? %></td>
    <!-- <td> <%= link_to "All Products", "#" ,class: "btn btn-primary" %> </td> -->
    <td> <%= pluralize(user.products.count, 'product') %> </td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="container">

<div class="row">
  <div class="col-md-5">

  </div>
 <div class="col-md-4">


   <h1 class="black-heading">
<br>
<i class="fa fa-user-circle text-center fa-random fa-1x" aria-hidden="true" ></i>
<br>
       <%= @user.name %>
   </h1>
 </div>

<div class="col-md-3">
</div>
</div>

  <h2 class="black-heading">  <%= @user.email %>
 </h2>

 <h2 class="black-heading">  <%= link_to @user.link %>  </h2>

    <br>


    <% @user.products.each do |product| %>
              <%= product %>
        <% end %>






</div>